### PR TITLE
allowed magnet links without dn

### PR DESCRIPTION
**Pull request by fertkir**

### CODE REVIEW

**Comment by angrynode** [comment]
Hello, sorry for the late reply and thank you so much for your contribution!

What's the usecase for a torrent without a name? I haven't given it too much thought, but i'd say erroring when no name is given is correct in most cases... however if you really need this, we can probably add a feature-flag? I'm not sure what the default should be, though.

Could you maybe separate the CI stuff from this PR? About the CI, running tests is always welcome. So is making sure that docs build without warnings. I'm not too fond of dependabot, on the other hand.

**Comment by angrynode** [comment]
After thinking about it, i'll make it the default behavior as you suggested. I won't take all the CI stuff though, i really hate that dependabot spamming PRs for 0 reason :)

**Comment by fertkir** [comment]
Apparently, not all trackers follow the spec. https://rutracker.org gives magnets without dn.

Thanks!

**Comment by angrynode** [comment]
OK i just released version v0.2 let me know if there's other problems you encounter or features you would find useful.

**Pull request closed without merging**
